export enum CurrencyType {
    TRY0 = 0, // Türk Lirası
    USD = 1,    // ABD Doları
    DEM = 2,    // Alman Markı
    AUD = 3,    // Avustralya Doları
    ATS = 4,    // Avusturya Şilini
    BEF = 5,    // Belçika Frangı
    DKK = 6,    // Danimarka Kronu
    FIM = 7,    // Fin Markkası
    FRF = 8,    // Fransız Frangı
    NLG = 9,    // Hollanda Florini
    SEK = 10,   // İsveç Kronu
    CHF = 11,   // İsviçre Frangı
    ITL = 12,   // İtalyan Lireti
    JPY = 13,   // Japon Yeni
    CAD = 14,   // Kanada Doları
    KWD = 15,   // Kuveyt Dinarı
    NOK = 16,   // Norveç Kronu
    GBP = 17,   // İngiliz Sterlini
    SAR = 18,   // S. Arabistan Riyali
    XEU = 19,   // Avrupa Para Birimi
    EUR = 20,   // Euro
    AZM = 21,   // Azerbaycan Manatı
    BRL = 22,   // Brezilya Cruzeirosu
    BGN = 23,   // Bulgar Levası
    CZK = 24,   // Çek Kuronu
    CNY = 25,   // Çin Yüeni
    EEK = 26,   // Estonya Kuronu
    GEL = 27,   // Gürcistan Larisi
    INR = 28,   // Hindistan Rupisi
    HKD = 29,   // Hongkong Doları
    IQD = 30,   // Irak Dinarı
    IRR = 31,   // İran Riyali
    IEP = 32,   // İrlanda Lirası
    ESP = 33,   // İspanyol Pesetası
    ILS = 34,   // İsrail Şekeli
    ISK = 35,   // İzlanda Kuronu
    CYP = 36,   // Kıbrıs Lirası
    KGS = 37,   // Kırgızistan Somu
    LVL = 38,   // Letonya Latsı
    LYD = 39,   // Libya Dinarı
    LBP = 40,   // Lübnan Lirası
    LTL = 41,   // Litvanya Litası
    LUF = 42,   // Lüksemburg Frangı
    HUF = 43,   // Macaristan Forinti
    MYR = 44,   // Malezya Ringgiti
    MXN = 45,   // Meksika Pesosu
    EGP = 46,   // Mısır Lirası
    BBD = 47,   // Barbados Doları
    PLN = 48,   // Polonya Zlotisi
    PTE = 49,   // Portekiz Escudosu
    ROL = 50,   // Romen Leyi
    RUB = 51,   // Rus Rublesi
    TWD = 52,   // Tayvan Doları
    TRY1 = 53,   // Türk Lirası
    JOD = 54,   // Ürdün Dinarı
    GRD = 55,   // Yunan Drahmisi
    ARS = 56,   // Arjantin Pesosu
    LAK = 57,   // Laos Kipi
    ADP = 58,   // Andorra Pesetası
    AED = 59,   // BAE Dirhemi
    AFN = 60,   // Afganistan Afganisi
    ALL = 61,   // Arnavutluk Leki
    ANG = 62,   // Hollanda Antilleri Florini
    AOA = 63,   // Angola Kwanzası
    BDT = 64,   // Bengaldeş Takası
    BHD = 65,   // Bahreyn Dinarı
    BIF = 66,   // Burundi Frangı
    BMD = 67,   // Bermuda Doları
    BND = 68,   // Brunei Doları
    BOB = 69,   // Bolivya Bolivianosu
    BSD = 70,   // Bahama Doları
    BTN = 71,   // Butan Lirası
    BWP = 72,   // Botswana Pulası
    BZD = 73,   // Belize Doları
    CLP = 74,   // Şili Pesosu
    COP = 75,   // Kolombiya Pesosu
    CRC = 76,   // Kosta Rika Kolonu
    CUP = 77,   // Küba Pesosu
    CVE = 78,   // Cape Verde Esküdosu
    DJF = 79,   // Cibuti Frangı
    DOP = 80,   // Dominik Pesosu
    DZD = 81,   // Cezayir Dinarı
    ECS = 82,   // Ekvator Sucresi
    ETB = 83,   // Etyopya Birri
    FJD = 84,   // Fiji Adaları Doları
    FKP = 85,   // Falkland Adaları Sterlini
    GHS = 86,   // Gana Cedisi
    GIP = 87,   // Cebelitarık Sterlini
    GMD = 88,   // Gambia Dalasisi
    GNF = 89,   // Gine Frangı
    GTQ = 90,   // Guatemala Quetzali
    GWP = 91,   // Gine-Bisse Pesosu
    GYD = 92,   // Guyana Doları
    HNL = 93,   // Honduras Lempirası
    HTG = 94,   // Haiti Gourdesi
    IDR = 95,   // Endonezya Rupisi
    JMD = 96,   // Jamaika Doları
    KES = 97,   // Kenya Şilingi
    KHR = 98,   // Kamboçya Rieli
    KMF = 99,   // Komor Frangi
    KPW = 100,  // Kuzey Kore Wonu
    KRW = 101,  // Güney Kore Wonu
    KYD = 102,  // Cayman Adaları Doları
    LKR = 103,  // Sri Lanka Rupisi
    LRD = 104,  // Liberya Doları
    LSL = 105,  // Lesoto Lotisi
    MAD = 106,  // Fas Dirhemi
    MNT = 107,  // Moğol Tugriki
    MOP = 108,  // Macau Patacası
    MRO = 109,  // Moritanya Ogiyası
    MTL = 110,  // Malta Lirası
    MUR = 111,  // Mauritius Rupisi
    MVR = 112,  // Maldiv Rufiyası
    MWK = 113,  // Malavi Kwachası
    MZN = 114,  // Mozambik Meticali
    NGN = 115,  // Nijerya Nairası
    NIO = 116,  // Nikaragua Cordoba Orosu
    NPR = 117,  // Nepal Rupisi
    NZD = 118,  // Yeni Zelanda Doları
    OMR = 119,  // Umman Riyali
    PAB = 120,  // Panama Balboası
    PEN = 121,  // Peru Solu
    PGK = 122,  // Papua Yeni Gine Kinası
    PHP = 123,  // Filipin Pesosu
    PKR = 124,  // Pakistan Rupisi
    PYG = 125,  // Paraguay Guaranisi
    QAR = 126,  // Katar Riyali
    RWF = 127,  // Ruanda Frangı
    SBD = 128,  // Solomon Adaları Doları
    SCR = 129,  // Seyşel Adaları Rupisi
    SDG = 130,  // Sudan Dinarı
    SGD = 131,  // Singapur Doları
    SHP = 132,  // St. Helen Lirası
    SLL = 133,  // Sierra Leone Leonesi
    SOS = 134,  // Somali Şilini
    SRD = 135,  // Surinam Florini
    STD = 136,  // Sao Tome Dobrası
    SVC = 137,  // El Salvador Colonu
    SYP = 138,  // Suriye Lirası
    SZL = 139,  // Swaziland Lilangenisi
    THB = 140,  // Tayland Bahtı
    TND = 141,  // Tunus Dinarı
    TPE = 142,  // Doğu Timor Esküdosu
    TTD = 143,  // Trinidad ve Tobago Doları
    TZS = 144,  // Tanzanya Şilini
    UGX = 145,  // Uganda Şilini
    UYU = 146,  // Uruguay Pesosu
    VEB = 147,  // Venezuella Bolivarı
    VND = 148,  // Vietnam Dongu
    WST = 149,  // Samoa Talası
    YDD = 150,  // Yemen Dinarı
    YER = 151,  // Yemen Riyali
    YUD = 152,  // Yugoslav Dinarı
    ZAR = 153,  // Güney Afrika Randı
    ZMK = 154,  // Zambia Kwachası
    ZWL = 155,  // Zimbabwe Doları
    KZT = 156,  // Kazak Tengesi
    UAH = 157,  // Ukrayna Grevniyası
    TMT = 158,  // Türkmenistan Manatı
    UZS = 159,  // Özbekistan Somu
    TL = 160,   // Türk Lirası
    RON = 161,  // Romen Yeni Leyi
    AZN = 162,  // Azerbaycan Yeni Manatı
    AMD = 164,  // Ermeni Dramı
    AWG = 165,  // Aruba Florini
    BAM = 166,  // Konvertibıl Mark
    BYR = 167,  // Beyaz Rusya Rublesi
    CDF = 168,  // Kongo Frangı
    ERN = 169,  // Eritre Nakfası
    HRK = 170,  // Hırvatistsan Kunası
    MDL = 171,  // Moldova Leyi
    MGA = 172,  // Malgaş ariarysi
    MKD = 173,  // Makedonya Dinarı
    MMK = 174,  // Kyat
    NAD = 175,  // Namibya Doları
    RSD = 176,  // Sırp Dinarı
    TJS = 177,  // Somoni
    TOP = 178,  // Pa'anga
    VEF = 179,  // Venezuela Bolivarı
    VUV = 180,  // Vanuatu Vatusu
    XAF = 181,  // Central African CFA Franc
    XCD = 182,  // Doğu Karayip Doları
    XOF = 183,  // CFA Frangı
    XPF = 184,  // CFP Frangı
    AU = 185,   // Altın
    AG = 186,   // Gümüş
    PT = 187,   // Platin
    PD = 188    // Paladyum
}